const CREATE_POST = 'POST/CREATE_POST';
const FETCH_POSTS = 'POST/FETCH_POSTS';
const SHOW_LOADER = 'POST/SHOW_LOADER';
const HIDE_LOADER = 'POST/HIDE_LOADER';
const SHOW_ALERT = 'POST/SHOW_ALERT';
const HIDE_ALERT = 'POST/HIDE_ALERT';

export {
  CREATE_POST,
  FETCH_POSTS,
  SHOW_LOADER,
  HIDE_LOADER,
  SHOW_ALERT,
  HIDE_ALERT,
};
